sudo: required

dist: trusty

language: python
python:
  - "2.7"
  - "3.6"
  - "3.5"

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions

env:
  matrix:
    - SCALA_VERSION=2.11.8 SPARK_VERSION=2.2.0 SPARK_BUILD="spark-${SPARK_VERSION}-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz"

before_install:
  - ./bin/download_travis_dependencies.sh

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-environment
  - conda install -c conda-forge pyspark=2.1.1

script:
  - python spark-xarray/reader.py

after_success:
  - bash <(curl -s https://codecov.io/bash)

